name: Docker Workflow
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          echo "Simulating Docker image build with tag: ${{ inputs.tag }}"
